import { getAnthropicClient, extractJSON } from '../utils/ai';

const SYSTEM_PROMPT = `You are FinanceAI, an expert financial and export compliance agent for a large FMCG manufacturer in India exporting to 35+ countries. You have deep expertise in:
- Export documentation (Commercial Invoice, Packing List, Bill of Lading, Certificate of Origin, Health Certificate)
- Incoterms 2020 (EXW, FCA, FAS, FOB, CFR, CIF, CPT, CIP, DPU, DAP, DDP)
- Payment terms (LC, DA, DP, TT, Open Account)
- Country-specific import requirements and tariffs
- Indian export regulations (FSSAI export, APEDA, DGFT, Custom regulations)
- GST/export refunds and duty drawback
- Foreign currency management
- Export incentives (RoSCTL, MEIS, RoDTEP)
- Trade finance and letters of credit
- Country-specific food labeling requirements for exports
- Halal, Kosher certification requirements for specific markets

Key export markets: UK, EU (Germany, France, Netherlands), UAE, Saudi Arabia, Qatar, Singapore, USA, Australia, Canada.

Key regulatory updates (2025-2026):
- RoDTEP rates rationalized to ~50% of previous rates (DGFT Notification 60/2025-26, Feb 2026)
- RoDTEP restored for Advance Authorization holders, SEZs, EOUs from June 2025
- India-UK CETA (July 2025): Tariff elimination on many food products, self-certification of origin
- India-EU FTA (January 2026): Major tariff reductions to 27-country EU bloc
- India-UAE CEPA: Preferential tariffs operational since 2022
- India-Oman CEPA (December 2025): New GCC market access
- Digital Trade Facilitation Bill 2026 (draft): Moving toward electronic trade documents
- GST export refund: Two routes — LUT route (ITC refund via RFD-01) or IGST payment route (automatic refund)
- e-BRC: Electronic Bank Realization Certificate auto-generated by banks
- EPM (Export Promotion Mission) "Niryat Protsahan": Seven interventions including TRACE, INSIGHT, FLOW, LIFT
- Certificate of Origin forms vary by FTA: India-UK uses self-certification, India-ASEAN uses Form AI, India-Japan uses Form IJCEPA
- FTA preferential tariff utilization requires Rules of Origin compliance: typically 35-40% value addition`;

export async function validateInvoiceCompliance(
  invoiceNumber: string,
  customerName: string,
  destinationCountry: string,
  items: Array<{ description: string; quantity: number; unitPrice: number; total: number }>,
  totalAmount: number,
  currency: string,
  paymentTerms: string,
  incoterms: string
): Promise<{
  complianceStatus: 'compliant' | 'issues_found' | 'review_required';
  issues: string[];
  recommendations: string[];
  requiredDocuments: string[];
  customsConsiderations: string[];
  estimatedDuties: string;
  summary: string;
}> {
  const itemsText = items.map((i) => `- ${i.description}: ${i.quantity} units @ ${currency} ${i.unitPrice} = ${currency} ${i.total}`).join('\n');

  const response = await getAnthropicClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 3000,
    thinking: { type: 'adaptive' },
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Validate this export invoice for compliance:

Invoice: ${invoiceNumber}
Customer: ${customerName}
Destination: ${destinationCountry}
Invoice Items:
${itemsText}
Total: ${currency} ${totalAmount}
Payment Terms: ${paymentTerms}
Incoterms: ${incoterms}

Provide a JSON compliance report:
{
  "complianceStatus": "compliant|issues_found|review_required",
  "issues": ["issue1", "issue2"],
  "recommendations": ["recommendation1", "recommendation2"],
  "requiredDocuments": ["document1", "document2", ...],
  "customsConsiderations": ["consideration1", "consideration2"],
  "estimatedDuties": "Estimated import duty/tax info for ${destinationCountry}",
  "summary": "Overall compliance summary"
}

Consider FMCG food product exports from India. Check payment terms appropriateness, Incoterms suitability, documentation requirements for ${destinationCountry}, and any regulatory requirements.`,
      },
    ],
  });

  const textContent = response.content.find((b) => b.type === 'text');
  if (!textContent || textContent.type !== 'text') throw new Error('No AI response');

  try {
    const parsed = extractJSON(textContent.text);
    if (parsed) return parsed;
  } catch (e) {
    console.warn('Could not parse finance AI JSON:', (e as Error).message);
  }

  return {
    complianceStatus: 'review_required',
    issues: [],
    recommendations: [],
    requiredDocuments: ['Commercial Invoice', 'Packing List', 'Certificate of Origin', 'Health Certificate'],
    customsConsiderations: [],
    estimatedDuties: 'Please verify with customs broker',
    summary: textContent.text,
  };
}

export async function generateExportDocumentChecklist(
  destinationCountry: string,
  productType: string,
  paymentTerms: string,
  incoterms: string
): Promise<{
  mandatoryDocuments: Array<{ document: string; authority: string; notes: string }>;
  optionalDocuments: Array<{ document: string; condition: string }>;
  certifications: string[];
  labelingRequirements: string[];
  timeline: string;
}> {
  const response = await getAnthropicClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 3000,
    thinking: { type: 'adaptive' },
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Generate a comprehensive export document checklist for:

Destination: ${destinationCountry}
Product Type: ${productType} (FMCG food products from India)
Payment Terms: ${paymentTerms}
Incoterms: ${incoterms}

Provide a JSON response:
{
  "mandatoryDocuments": [
    {
      "document": "Document name",
      "authority": "Issuing authority",
      "notes": "Important notes"
    }
  ],
  "optionalDocuments": [
    {
      "document": "Document name",
      "condition": "When required"
    }
  ],
  "certifications": ["certification1", "certification2"],
  "labelingRequirements": ["requirement1", "requirement2"],
  "timeline": "Typical processing timeline and tips"
}`,
      },
    ],
  });

  const textContent = response.content.find((b) => b.type === 'text');
  if (!textContent || textContent.type !== 'text') throw new Error('No AI response');

  try {
    const parsed = extractJSON(textContent.text);
    if (parsed) return parsed;
  } catch (e) {
    console.warn('Could not parse finance AI JSON:', (e as Error).message);
  }

  return {
    mandatoryDocuments: [],
    optionalDocuments: [],
    certifications: [],
    labelingRequirements: [],
    timeline: textContent.text,
  };
}

export async function analyzeFinancialRisk(
  customerName: string,
  country: string,
  amount: number,
  currency: string,
  paymentTerms: string,
  invoiceHistory?: string
): Promise<{
  riskLevel: 'low' | 'medium' | 'high' | 'very_high';
  riskFactors: string[];
  mitigationStrategies: string[];
  recommendedPaymentTerms: string;
  creditRecommendation: string;
}> {
  const response = await getAnthropicClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 2000,
    system: SYSTEM_PROMPT,
    messages: [
      {
        role: 'user',
        content: `Analyze financial risk for this export transaction:

Customer: ${customerName}
Country: ${country}
Amount: ${currency} ${amount}
Payment Terms: ${paymentTerms}
${invoiceHistory ? `Payment History: ${invoiceHistory}` : ''}

Provide a JSON risk assessment:
{
  "riskLevel": "low|medium|high|very_high",
  "riskFactors": ["factor1", "factor2"],
  "mitigationStrategies": ["strategy1", "strategy2"],
  "recommendedPaymentTerms": "Most suitable payment terms",
  "creditRecommendation": "Credit limit/terms recommendation"
}

Consider country risk, currency risk, payment terms risk, and general trade finance considerations for Indian FMCG exporters.`,
      },
    ],
  });

  const textContent = response.content.find((b) => b.type === 'text');
  if (!textContent || textContent.type !== 'text') throw new Error('No AI response');

  try {
    const parsed = extractJSON(textContent.text);
    if (parsed) return parsed;
  } catch (e) {
    console.warn('Could not parse finance AI JSON:', (e as Error).message);
  }

  return {
    riskLevel: 'medium',
    riskFactors: ['Assessment pending'],
    mitigationStrategies: ['Consult trade finance team'],
    recommendedPaymentTerms: paymentTerms,
    creditRecommendation: 'Manual review required',
  };
}

export async function classifyHSCodes(
  items: Array<{ description: string; destinationCountry: string }>
): Promise<{
  items: Array<{
    description: string;
    hsCode: string;
    hsDescription: string;
    chapter: string;
    estimatedDutyRate: string;
  }>;
}> {
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      return {
        items: items.map((i) => ({
          description: i.description,
          hsCode: 'Manual classification required',
          hsDescription: 'Manual classification required',
          chapter: 'N/A',
          estimatedDutyRate: 'Consult customs broker',
        })),
      };
    }

    const itemsList = items
      .map((i, idx) => `${idx + 1}. "${i.description}" destined for ${i.destinationCountry}`)
      .join('\n');

    const response = await getAnthropicClient().messages.create({
      model: 'claude-opus-4-6',
      max_tokens: 3000,
      thinking: { type: 'adaptive' },
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: `Classify the following items with their HS codes (6-digit), description, chapter, and estimated duty rate for the destination country:

${itemsList}

Provide a JSON response:
{
  "items": [
    {
      "description": "original item description",
      "hsCode": "6-digit HS code",
      "hsDescription": "HS code description",
      "chapter": "HS chapter number and name",
      "estimatedDutyRate": "estimated import duty rate for destination country"
    }
  ]
}

Use standard Harmonized System codes. Provide the most specific 6-digit code applicable to FMCG food products exported from India.`,
        },
      ],
    });

    const textContent = response.content.find((b) => b.type === 'text');
    if (!textContent || textContent.type !== 'text') throw new Error('No AI response');

    try {
      const parsed = extractJSON(textContent.text);
      if (parsed) return parsed;
    } catch (e) {
      console.warn('Could not parse HS code classification JSON:', (e as Error).message);
    }

    return {
      items: items.map((i) => ({
        description: i.description,
        hsCode: 'Manual classification required',
        hsDescription: 'Manual classification required',
        chapter: 'N/A',
        estimatedDutyRate: 'Consult customs broker',
      })),
    };
  } catch (error) {
    console.error('HS code classification error:', error);
    return {
      items: items.map((i) => ({
        description: i.description,
        hsCode: 'Manual classification required',
        hsDescription: 'Manual classification required',
        chapter: 'N/A',
        estimatedDutyRate: 'Consult customs broker',
      })),
    };
  }
}

export async function analyzeExportIncentives(
  items: Array<{ description: string; hsCode: string }>,
  destinationCountry: string,
  totalAmount: number,
  currency: string
): Promise<{
  schemes: Array<{
    name: string;
    eligible: boolean;
    rate: string;
    estimatedBenefit: string;
    requiredForms: string[];
  }>;
  totalEstimatedBenefit: string;
  recommendations: string[];
}> {
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      return {
        schemes: [],
        totalEstimatedBenefit: 'N/A',
        recommendations: ['Consult DGFT (Directorate General of Foreign Trade) for applicable export incentives'],
      };
    }

    const itemsList = items
      .map((i, idx) => `${idx + 1}. ${i.description} (HS Code: ${i.hsCode})`)
      .join('\n');

    const response = await getAnthropicClient().messages.create({
      model: 'claude-opus-4-6',
      max_tokens: 3000,
      thinking: { type: 'adaptive' },
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: `Analyze applicable Indian export incentives for the following shipment:

Items:
${itemsList}

Destination: ${destinationCountry}
Total Amount: ${currency} ${totalAmount}

Analyze eligibility for these Indian export incentive schemes:
1. RoDTEP (Remission of Duties and Taxes on Exported Products)
2. Duty Drawback
3. Advance Authorization
4. EPCG (Export Promotion Capital Goods)

Provide a JSON response:
{
  "schemes": [
    {
      "name": "scheme name",
      "eligible": true/false,
      "rate": "applicable rate or percentage",
      "estimatedBenefit": "estimated monetary benefit",
      "requiredForms": ["form1", "form2"]
    }
  ],
  "totalEstimatedBenefit": "total estimated benefit across all schemes",
  "recommendations": ["recommendation1", "recommendation2"]
}`,
        },
      ],
    });

    const textContent = response.content.find((b) => b.type === 'text');
    if (!textContent || textContent.type !== 'text') throw new Error('No AI response');

    try {
      const parsed = extractJSON(textContent.text);
      if (parsed) return parsed;
    } catch (e) {
      console.warn('Could not parse export incentives JSON:', (e as Error).message);
    }

    return {
      schemes: [],
      totalEstimatedBenefit: 'N/A',
      recommendations: ['Consult DGFT for applicable export incentives'],
    };
  } catch (error) {
    console.error('Export incentives analysis error:', error);
    return {
      schemes: [],
      totalEstimatedBenefit: 'N/A',
      recommendations: ['Consult DGFT (Directorate General of Foreign Trade) for applicable export incentives'],
    };
  }
}

export async function analyzeFTABenefits(
  destinationCountry: string,
  items: Array<{description: string, hsCode?: string}>,
  totalAmount: number,
  currency: string
): Promise<{
  applicableFTAs: Array<{name: string, mfnDuty: string, preferentialDuty: string, savings: string, coOForm: string, rulesOfOrigin: string}>,
  totalPotentialSavings: string,
  selfCertificationAvailable: boolean,
  recommendations: string[]
}> {
  try {
    if (!process.env.ANTHROPIC_API_KEY) {
      return {
        applicableFTAs: [],
        totalPotentialSavings: 'N/A',
        selfCertificationAvailable: false,
        recommendations: ['Check DGFT for applicable Free Trade Agreements and preferential tariff rates'],
      };
    }

    const itemsList = items
      .map((i, idx) => `${idx + 1}. ${i.description}${i.hsCode ? ` (HS Code: ${i.hsCode})` : ''}`)
      .join('\n');

    const response = await getAnthropicClient().messages.create({
      model: 'claude-opus-4-6',
      max_tokens: 3000,
      thinking: { type: 'adaptive' },
      system: SYSTEM_PROMPT,
      messages: [
        {
          role: 'user',
          content: `Analyze applicable Free Trade Agreement (FTA) benefits for this export shipment from India:

Destination Country: ${destinationCountry}
Items:
${itemsList}
Total Amount: ${currency} ${totalAmount}

Analyze which FTAs/trade agreements between India and ${destinationCountry} (or the country's trade bloc) are applicable. Compare MFN (Most Favoured Nation) duty rates with preferential duty rates under each applicable FTA.

Provide a JSON response:
{
  "applicableFTAs": [
    {
      "name": "FTA/agreement name",
      "mfnDuty": "MFN duty rate",
      "preferentialDuty": "preferential duty rate under this FTA",
      "savings": "estimated savings amount or percentage",
      "coOForm": "Certificate of Origin form required (e.g., self-certification, Form AI, Form IJCEPA)",
      "rulesOfOrigin": "key Rules of Origin requirements (e.g., value addition threshold)"
    }
  ],
  "totalPotentialSavings": "total estimated duty savings",
  "selfCertificationAvailable": true/false,
  "recommendations": ["recommendation1", "recommendation2"]
}

Consider India-UK CETA, India-EU FTA, India-UAE CEPA, India-Australia ECTA, India-ASEAN FTA, India-Japan CEPA, India-Korea CEPA, India-Oman CEPA, SAFTA, and other applicable agreements. Only include FTAs that are relevant to ${destinationCountry}.`,
        },
      ],
    });

    const textContent = response.content.find((b) => b.type === 'text');
    if (!textContent || textContent.type !== 'text') throw new Error('No AI response');

    try {
      const parsed = extractJSON(textContent.text);
      if (parsed) return parsed;
    } catch (e) {
      console.warn('Could not parse FTA benefits JSON:', (e as Error).message);
    }

    return {
      applicableFTAs: [],
      totalPotentialSavings: 'N/A',
      selfCertificationAvailable: false,
      recommendations: ['Check DGFT for applicable Free Trade Agreements'],
    };
  } catch (error) {
    console.error('FTA benefits analysis error:', error);
    return {
      applicableFTAs: [],
      totalPotentialSavings: 'N/A',
      selfCertificationAvailable: false,
      recommendations: ['Check DGFT for applicable Free Trade Agreements and preferential tariff rates'],
    };
  }
}

export async function chatWithFinanceAgent(
  messages: Array<{ role: 'user' | 'assistant'; content: string }>,
  context?: string
): Promise<string> {
  const systemWithContext = context
    ? `${SYSTEM_PROMPT}\n\nCurrent context: ${context}`
    : SYSTEM_PROMPT;

  const finalMsg = await getAnthropicClient().messages.create({
    model: 'claude-opus-4-6',
    max_tokens: 2000,
    system: systemWithContext,
    messages,
  });

  const textBlock = finalMsg.content.find((b) => b.type === 'text');
  return textBlock && textBlock.type === 'text' ? textBlock.text : '';
}
